### ISSUE TITLE
Language name

### ISSUE THREAD

**Issue by apertix** [psi-lang/psi#4]
I don't think it's a very good name, could get easily confused with pressure per square inch. I think a re-brand is in order.

**Comment by hvze** [comment]
There is also D, 
Python (an animal)
Java (both a place and some sort of drink)
Lily (a flower)
Go (a common english word!)
and a ton more.

My point is, languages don't need to rebrand themselves, as long as people can determine the difference between the actual "thing" and the language, its fine.
(psi-lang is the search term people should use, same for Golang and io-lang)

**Comment by apertix** [comment]
See, there is no language that is an acronym though. It's really confusing dude.

**Comment by hvze** [comment]
Being that my example above was an actual word (not an acronym) please explain to me how thats less confusing than an acronym?
